### PR TITLE
Adding CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by TavoNiievez**
Co-authored by: @ThomasLandauer

### CODE REVIEW

**Comment by TavoNiievez** [comment]
@ThomasLandauer

**Comment by TavoNiievez** [comment]
@ThomasLandauer something else i have omitted here?

Is everything understood?

**Comment by ThomasLandauer** [comment]
https://github.com/Codeception/symfony-module-tests/blob/main/README.md is perfect now - I like it! :-)

I couldn't find a way to edit `CONTRIBUTING.md` :-( Could you merge it so I can send PR's?

**Comment by TavoNiievez** [comment]
you can send a PR to my fork https://github.com/TavoNiievez/module-symfony/tree/contributing

**Comment by ThomasLandauer** [comment]
Great - see https://github.com/TavoNiievez/module-symfony/pull/1 :-)

**Comment by ThomasLandauer** [comment]
I forgot what https://github.com/Codeception/symfony-module-tests/blob/main/README.md contains ;-) Now step 1 overlaps with it. Suggestion:
* Can we move the "fork" part to https://github.com/Codeception/symfony-module-tests/blob/main/README.md ? I assume that forking it is *always* a good idea, isn't it?  
  Then step 1 would become `branch` and the 3 steps from https://github.com/Codeception/module-symfony/pull/84#issuecomment-746863733

Where can I send PR's to `CONTRIBUTE.md` now?

**Comment by TavoNiievez** [comment]
You won't always use `Codeception/symfony-module-tests` to make changes or submit PR, it may just be to explore how some method works in a simpler project or another Symfony version. (that's why some of these projects were also called 'demo').

> Where can I send PR's to `CONTRIBUTE.md` now?

In [the same place](https://github.com/TavoNiievez/module-symfony/blob/contributing/CONTRIBUTING.md).

**Comment by ThomasLandauer** [comment]
Regarding https://github.com/Codeception/symfony-module-tests/pull/5 :
* I'm guessing that `git pull` and `git rebase` don't do any harm, even if the fork is fresh anyway?
* If you agree in principle with this way, then I'll adapt (i.e. simplify) step 1 at https://github.com/TavoNiievez/module-symfony/blob/contributing/CONTRIBUTING.md accordingly.

**Comment by TavoNiievez** [comment]
OK, the only line that should be added to `symfony-module-tests` is: 
```
'If you are using this project to create a Pull Request to the Symfony Module (see `CONTRIBUTING.md`):'
```
The `git pull` `git rebase` process is just a special case where you've forked a long time ago and the project has been updated since then. It should be just a ***very small*** note and should be in the contribution guides and not in the test project `README.md`.

**Comment by ThomasLandauer** [comment]
See https://github.com/Codeception/module-symfony/pull/85 and sorry for the bad title ;-)

* General: It got a little more complicated now ("Continue with step 2+3..."). But what I suggested before (changing README.md) was equally confusing ;-)
* About `git pull` and `rebase`: Explaining in detail when this is needed and when not, is more complicated than just leaving it in. Main argument: Those who know what they are doing, won't paste those two lines anyway ;-) And for the others it doesn't do any harm.
* Please update `git push --set-upstream origin new_feature`. Due to `git remote add upstream...` you can probably remove something from it.

**Comment by TavoNiievez** [comment]
@ThomasLandauer I think the [current state of the file](https://github.com/TavoNiievez/module-symfony/blob/contributing/CONTRIBUTING.md) is pretty good.

Unless there is something that is really wrong i think we can leave it as it is now so as not to overthink things.

**Comment by ThomasLandauer** [comment]
@TavoNiievez

1. Should `CONTRIBUTING.md` be mentioned at https://codeception.com/docs/modules/Symfony too?

2. And what is https://codeception.com/docs/modules/Symfony#Demo-Project ?

**Comment by TavoNiievez** [comment]
@ThomasLandauer 

I do not update the Codeception page, the link to the test/demo project has [already been updated](https://github.com/Codeception/module-symfony/commit/32ebb7ad55b4263cba5624c939f94d3a0ce327da).

btw, thanks again for helping with this.

**Pull request merged**
