### PR TITLE
Test against PHP 8.4

### PR DESCRIPTION
**Pull request by W0rma**

### CODE REVIEW

**Review by TavoNiievez — APPROVED** [review]
Thank you!

**Comment by W0rma** [comment]
@TavoNiievez Do you plan to tag a new version? 

The new tag would also contain https://github.com/Codeception/module-symfony/pull/197 which fixes some deprecation warnings in PHP 8.4.

**Comment by TavoNiievez** [comment]
Currently in the main branch there are some changes related to #198, #200 and https://github.com/Codeception/symfony-module-tests/pull/27 

I need those tests to be ready before making a tag.

**Comment by TavoNiievez** [comment]
Released as [3.5.0](https://github.com/Codeception/module-symfony/releases/tag/3.5.0).

**Pull request merged**
